
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "@/components/header";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "sonner";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";

import type { Metadata } from "next";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Divide and Conquer",
  description: "Generated by Gaurav",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>
            <Head />
            <Toaster richColors position="top-right" />
            <main className="min-h-screen">{children}</main>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
